### ISSUE TITLE
Custom field extension to create a simple Array of Dictionaries

### ISSUE THREAD

**Issue by r-a-o** [contentstack/extensions#1]
I have explored all types of fields available on ContentStack and have failed to create a field that would capture data in the below shown format.

```
"groups": [
    {
      "name": "Group A",
      "code": "A", 
      "teams": [
          "blt40ea7229810f56fc",  // Reference to team
          "bltb520521efc452673"  // Reference to team
        ]
    },
    {
      "name": "Group B",
      "code": "B",
      "teams": [
          "blt4b5928bfed7ef9d5"  // Reference to team
        ]
    }
  ]
```

Is there any way to achieve this simple data structure?

if not, how do I create a custom field type that would let me capture data in `Array of Dictionaries` way?

PS:
The closest I can get is by using Modular Blocks, I was able to achieve the following format,

```
"groups": [
    {
      "A": {
        "teams": [
          "blt40ea7229810f56fc",
          "bltb520521efc452673"
        ]
      }
    },
    {
      "B": {
        "teams": [
          "blt4b5928bfed7ef9d5"
        ]
      }
    }
  ]
```
Note that using Modular Blocks immediately made it a nested dictionary (ie., unnecessarily one level deeper).

We'd greatly appreciate any help. 
Thanks

**Comment by kevalvegeto** [comment]
Hi,

For creating multiple objects with same set of fields, we would recommend group filed which has multiple attribute checked.

Your contenttype should look like the following image
![contenttype](https://user-images.githubusercontent.com/7731787/52785767-d3446c00-307e-11e9-9157-f1234c51bdf7.png)

and your sample entry like shown below, you can add multiple elements in the group with same schema by clicking on plus button
![edit entry shopify contentstack](https://user-images.githubusercontent.com/7731787/52785834-02f37400-307f-11e9-9f73-0d53c3626f03.png)

**Comment by r-a-o** [comment]
Ah, gotcha. This requires creating a contenttype and then using that contenttype in my main contenttype. I was hoping there was an easier way, since the moment I create a sub contenttype, I have to populate data separately for it. 
What I mean is, if it were a `field` in my main contenttype, I'd be filling just one form while creating data. (now I have to populate my groups separately and then open my main contenttype and link those groups)

**Comment by kevalvegeto** [comment]
Hi, You need not create a new contenttype, you can add the group field in your main contenttype

**Comment by r-a-o** [comment]
But the group field doesn't let you order items ie., I won't be able to say, show 'Group A' first, then 'Group B' here.

**Comment by r-a-o** [comment]
Ah.. now I see what you mean. `Group` can be made "multiple" and I can repeat items in the group while adding entry. Awesome.
